version: "3.9"

services:
  bb-pinger:
    image: busybox
    command: ping wapp-svc
    depends_on:
      - wapp-svc

  wapp-svc:
    #image: wapp
    image: a0z9/dock:wapp.0.5
    #image: dock01:5001/wapp:0.5
    ports:
      - "8090:8080"
    environment:
      - DOCK_HOST=dock03-compose
      - VERSION=1.2

    volumes:
      - wapp:/home/data

#    hostname: wapp1

volumes:
  wapp: {}

