FROM nodejscn/node

ENV DOCK_HOST="Training"

LABEL maintainer=a0z9@rambler.ru

WORKDIR /var/wapp
RUN mkdir logs

COPY wapp-log.js .

RUN date ; echo test wapp dockerfile

EXPOSE 8080
VOLUME /var/wapp/

ENTRYPOINT ["node", "wapp-log.js"]




