#FROM node:12
FROM node:slim
  
LABEL maintainer="a0z9@rambler.ru"

RUN node --version

WORKDIR /usr/bin

# Debian 9/stretch moved to archive.debian.org (end of April 2023)
# Correction below
#RUN sed -i -e 's/deb.debian.org/archive.debian.org/g'  -e 's|security.debian.org|archive.debian.org/|g'  -e '/stretch-updates/d' /etc/apt/sources.list

RUN apt-get update && apt-get install -y apt-utils && apt-get install -y curl

#RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -

RUN apt-get update && apt-get install -y npm  

WORKDIR /var/www/app

RUN npm init -y && npm install --save express body-parser mariadb

COPY ./wapp_db.js .

ENTRYPOINT ["node", "wapp_db.js"]

