#!/bin/bash

tput setaf 2 && echo "Preparing to install..." && tput setaf 7

sudo yum remove -y docker docker-client-latest docker-client docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine docker.io containerd runc
sudo yum makecache


sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo


tput setaf 2 && echo "Installing Docker..." && tput setaf 7

sudo yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

sudo systemctl enable docker
sudo systemctl start docker

tput setaf 2 && echo "Add user $USER to docker group..." && tput setaf 7

sudo usermod -aG docker $USER
newgrp docker

tput setaf 2 && echo "Finished." && tput setaf 7
